name: build-docs
on:
  workflow_dispatch:
  push:
    branches:
      - main

jobs:
  publish:
    name: Publish to the retype branch
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-dotnet@v1
        with:
          dotnet-version: 5.0.x
      - uses: retypeapp/action-build@v1
      - uses: retypeapp/action-github-pages@v1
        with:
          branch: docs
          directory: docs
          update-branch: true